const assert = require('node:assert/strict')
const { X509Certificate } = require('node:crypto')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const JSZip = require('../../band-app/node_modules/jszip')

const root = path.resolve(__dirname, '..')
const rpk = path.join(root, 'dist', 'io.github.rogerlang.codexquota.validation.release.0.6.5.rpk')
const cert = path.join(root, 'sign', 'release', 'certificate.pem')

test('built Stage 03A probe has validation identity, file feature and bridge code', async () => {
  const bytes = fs.readFileSync(rpk)
  const zip = await JSZip.loadAsync(bytes)
  const manifest = JSON.parse(await zip.file('manifest.json').async('string'))
  assert.equal(manifest.package, 'io.github.rogerlang.codexquota.validation')
  assert.equal(manifest.config.designWidth, 336)
  assert.ok(manifest.features.some((item) => item.name === 'system.file'))
  assert.ok(manifest.features.some((item) => item.name === 'system.interconnect'))
  const app = await zip.file('app.js').async('string')
  assert.match(app, /watchface_sequence\.txt/)
  assert.match(app, /stage03_state_ack/)
  const certificate = new X509Certificate(fs.readFileSync(cert))
  assert.ok(bytes.indexOf(certificate.raw) >= 0, 'RPK signature block should contain the validation certificate')
})
