const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('Stage 03D reuses the proven black index relay and terminates after ACK dispatch', () => {
  const manifest = JSON.parse(read('src/manifest.json'))
  assert.equal(manifest.router.entry, 'pages/index')
  assert.equal(manifest.router.pages['pages/index'].component, 'index')
  const index = read('src/pages/index/index.ux')
  assert.match(index, /background-color:\s*#000000/i)
  const app = read('src/app.ux')
  assert.match(app, /import app from '@system\.app'/)
  assert.match(app, /connection\.send\(\{\s*data:/s)
  assert.match(app, /returnToWatchfaceSoon\(\)/)
  assert.match(app, /app\.terminate\(\)/)
  assert.doesNotMatch(app, /success:\s*returnToWatchfaceSoon/)
})
